import type { RolePageContent } from "@/types/role";

import {
  API_SECURITY_ENGINEER_ENRICHED,
  APPSEC_ENGINEER_ENRICHED,
  AZURE_SECURITY_ENGINEER_ENRICHED,
  GRC_ANALYST_ENRICHED,
  PENTESTER_ENRICHED,
  SOC_ANALYST_ENRICHED,
} from "@/lib/roles/enriched";
import {
  SALARY_APPSEC,
  SALARY_API_SECURITY,
  SALARY_AZURE,
  SALARY_GRC,
  SALARY_PENTEST,
  SALARY_SOC,
} from "@/lib/roles/shared-snippets";

export const V1_ROLE_PAGES: readonly RolePageContent[] = [
  {
    slug: "soc-analyst",
    name: "SOC Analyst",
    domain: "Defensive Security",
    domainId: "defensive-security",
    level: "Entry to Mid",
    v1: true,
    cabinetPath: "soc",
    dayToDay:
      "You watch alerts, decide what is noise and what is real, and escalate when something needs a human. Most of your day is log review, ticket updates, and short investigations. When an incident lands, you are often the first person to touch it.",
    background:
      "Helpdesk, IT support, or networking experience helps. Complete beginners can start here if they finish foundations first. You need patience for repetitive triage and curiosity when something does not fit the pattern.",
    typicalWeek: [
      "Monday: Shift handover, review overnight alerts, tune one noisy detection rule.",
      "Tuesday: Phishing queue, write up two investigations with headers and sandbox results.",
      "Wednesday: Threat intel brief, enrich IOCs from yesterday's case.",
      "Thursday: Hunt block: test a hypothesis in the SIEM with a new query.",
      "Friday: Document a closed incident and update the team runbook.",
    ],
    salaries: SALARY_SOC,
    industries: [
      "Managed security service providers (MSSPs)",
      "Banks and financial services",
      "Healthcare",
      "Retail and e-commerce",
      "Government and critical infrastructure",
      "Technology companies with in-house SOCs",
    ],
    toolsFree: [
      "Wazuh (SIEM and EDR)",
      "Elastic Stack",
      "Sigma rules",
      "Velociraptor",
      "Wireshark",
      "VirusTotal (free tier)",
    ],
    toolsEnterprise: [
      "Splunk Enterprise Security",
      "Microsoft Sentinel",
      "CrowdStrike Falcon",
      "Palo Alto Cortex XSIAM",
      "IBM QRadar",
    ],
    certs: [
      {
        name: "CompTIA Security+",
        note: "Useful for your first security job. Covers breadth, not depth. Employers still ask for it at entry level.",
      },
      {
        name: "BTL1",
        note: "Practical blue team cert with hands-on labs. Better signal than Security+ alone if you already have IT experience.",
      },
      {
        name: "GIAC GCIA / GCIH",
        note: "Stronger once you are working in a SOC. Expensive. Worth it if your employer pays.",
      },
    ],
    careerProgression: [
      "SOC Analyst (Tier 1)",
      "SOC Analyst (Tier 2) / Senior Analyst",
      "Threat Hunter or Incident Responder",
      "SOC Team Lead or Detection Engineering",
    ],
    modules: [
      { name: "SIEM Fundamentals", status: "coming-soon" },
      { name: "Detection Engineering", status: "coming-soon" },
      { name: "Log Analysis and Investigation", status: "coming-soon" },
      { name: "Incident Response", status: "coming-soon" },
      { name: "Threat Hunting", status: "coming-soon" },
      { name: "Email Threat Analysis", status: "coming-soon" },
      { name: "Endpoint Triage", status: "coming-soon" },
      { name: "SOC Capstone", status: "coming-soon" },
    ],
    ...SOC_ANALYST_ENRICHED,
  },
  {
    slug: "penetration-tester",
    name: "Penetration Tester",
    domain: "Offensive Security",
    domainId: "offensive-security",
    level: "Mid to Senior",
    v1: true,
    cabinetPath: "pentest",
    dayToDay:
      "You test systems someone else owns, with written permission and clear rules. Days mix recon, manual testing, exploitation, and writing findings so a client can fix issues. You spend as much time explaining risk as running tools.",
    background:
      "IT or SOC experience helps before going full offensive. Developers often pick up web testing fast. You need clear writing skills and discipline to stay in scope. This is not the same as bug bounty hunting on your own schedule.",
    typicalWeek: [
      "Monday: Kickoff call, confirm scope and rules of engagement.",
      "Tuesday: External recon and vulnerability scanning, triage results.",
      "Wednesday: Manual web testing in Burp, chain two findings.",
      "Thursday: Internal segment testing or privilege escalation path.",
      "Friday: Draft executive summary and technical findings for review.",
    ],
    salaries: SALARY_PENTEST,
    industries: [
      "Consultancies and boutique pentest firms",
      "Big four and advisory practices",
      "Internal red team at large enterprises",
      "SaaS vendors (product security with offensive skills)",
      "Government and defence contractors",
    ],
    toolsFree: [
      "Kali Linux",
      "nmap",
      "Burp Suite Community",
      "OWASP ZAP",
      "Metasploit",
      "BloodHound Community Edition",
    ],
    toolsEnterprise: [
      "Burp Suite Professional",
      "Cobalt Strike (licensed engagements)",
      "Nessus Professional / Tenable.io",
      "Core Impact",
      "Pentera / PTC (automation platforms)",
    ],
    certs: [
      {
        name: "eJPT / PNPT",
        note: "Good proving grounds before OSCP. Cheaper entry into practical offensive exams.",
      },
      {
        name: "OSCP",
        note: "Still the most recognised practical pentest cert. Hard. Worth the effort if you want consulting work.",
      },
      {
        name: "CREST CRT / CHECK",
        note: "Required for many UK government and regulated client tests.",
      },
    ],
    careerProgression: [
      "Junior Penetration Tester",
      "Penetration Tester",
      "Senior Consultant / Lead Tester",
      "Red Teamer or Offensive Security Lead",
    ],
    modules: [
      { name: "Pentest Lab Setup", status: "coming-soon" },
      { name: "Reconnaissance and Enumeration", status: "coming-soon" },
      { name: "Vulnerability Assessment", status: "coming-soon" },
      { name: "Web Application Testing", status: "coming-soon" },
      { name: "Network Scanning", status: "coming-soon" },
      { name: "Exploitation", status: "coming-soon" },
      { name: "Post-Exploitation", status: "coming-soon" },
      { name: "Reporting and Communication", status: "coming-soon" },
    ],
    ...PENTESTER_ENRICHED,
  },
  {
    slug: "azure-security-engineer",
    name: "Azure Security Engineer",
    domain: "Cloud and Infrastructure Security",
    domainId: "cloud-infrastructure-security",
    level: "Mid to Senior",
    v1: true,
    cabinetPath: "azure",
    dayToDay:
      "You secure Azure tenants: identity, networking, logging, and workloads. Typical work includes reviewing Secure Score, tuning Sentinel rules, fixing misconfigurations, and supporting incident response in the cloud. Stakeholders are infra and dev teams as much as security leadership.",
    background:
      "Azure administrator, Windows admin, or SOC background with cloud exposure fits well. You should be comfortable with Entra ID, networking basics, and reading KQL. Pure GRC profiles struggle without hands-on lab time.",
    typicalWeek: [
      "Monday: Review Defender for Cloud recommendations for two subscriptions.",
      "Tuesday: Build or tune Sentinel analytics rules from recent incidents.",
      "Wednesday: Conditional Access change request and PIM activation review.",
      "Thursday: Network security group and Private Endpoint design session.",
      "Friday: Compliance export for CIS benchmark and gap discussion with GRC.",
    ],
    salaries: SALARY_AZURE,
    industries: [
      "Enterprises on Microsoft 365 and Azure",
      "Managed service providers",
      "Consulting and system integrators",
      "SaaS companies on Azure",
      "Public sector cloud migration programmes",
    ],
    toolsFree: [
      "Microsoft Defender for Cloud (free tier features)",
      "Entra ID free tier / dev tenants",
      "Open source KQL community queries",
      "Prowler / ScoutSuite (multi-cloud posture)",
      "Terraform (lab environments)",
    ],
    toolsEnterprise: [
      "Microsoft Sentinel",
      "Microsoft Defender for Cloud (full)",
      "Entra ID PIM and Conditional Access",
      "Azure Firewall and DDoS Protection",
      "Purview and Defender for Office 365",
    ],
    certs: [
      {
        name: "AZ-500",
        note: "The baseline Microsoft security cert. Matches much of this path. Do the labs, not just the videos.",
      },
      {
        name: "SC-200",
        note: "Sentinel and defender operations focus. Good after you have SOC or cloud experience.",
      },
      {
        name: "SC-300",
        note: "Identity-heavy. Useful if you own Entra ID and PIM for your organisation.",
      },
    ],
    careerProgression: [
      "Cloud Security Engineer (Azure)",
      "Senior Cloud Security Engineer",
      "Cloud Security Architect",
      "Security Architect or CISO track with cloud specialism",
    ],
    modules: [
      { name: "Identity and Access Management", status: "coming-soon" },
      { name: "Microsoft Sentinel", status: "coming-soon" },
      { name: "Defender for Cloud", status: "coming-soon" },
      { name: "Network Security in Azure", status: "coming-soon" },
      { name: "Privileged Identity Management", status: "coming-soon" },
      { name: "Cloud Incident Response", status: "coming-soon" },
      { name: "Compliance and Governance", status: "coming-soon" },
      { name: "Cloud Security Capstone", status: "coming-soon" },
    ],
    ...AZURE_SECURITY_ENGINEER_ENRICHED,
  },
  {
    slug: "grc-analyst",
    name: "GRC Analyst",
    domain: "Governance, Risk and Compliance",
    domainId: "governance-risk-compliance",
    level: "Entry to Mid",
    v1: true,
    cabinetPath: "grc",
    dayToDay:
      "You map controls to frameworks, maintain risk registers, chase evidence for audits, and help teams understand what policy actually requires. Less terminal time than a SOC role, more spreadsheets, workshops, and written artefacts.",
    background:
      "Audit, risk, legal, or IT governance backgrounds transfer well. Technical curiosity helps when reviewers challenge control design. You do not need to exploit systems, but you must understand how they fail.",
    typicalWeek: [
      "Monday: Update risk register from last week's project reviews.",
      "Tuesday: Workshop with engineering on a new vendor assessment.",
      "Wednesday: Draft policy exception with compensating controls.",
      "Thursday: Collect audit evidence for access management controls.",
      "Friday: ISO 27001 gap review session with external consultant.",
    ],
    salaries: SALARY_GRC,
    industries: [
      "Financial services and insurance",
      "Healthcare and pharma",
      "Technology and SaaS (SOC 2 programmes)",
      "Professional services",
      "Government and regulated utilities",
    ],
    toolsFree: [
      "Open source risk register templates",
      "NIST and ISO public publications",
      "OWASP for control context",
      "Spreadsheets and diagramming (Draw.io)",
    ],
    toolsEnterprise: [
      "ServiceNow GRC / IRM",
      "Archer",
      "OneTrust",
      "Vanta / Drata (compliance automation)",
      "Microsoft Purview Compliance Manager",
    ],
    certs: [
      {
        name: "ISO 27001 Lead Implementer / Auditor",
        note: "Valued in UK and EU organisations running ISO programmes. Teaches the standard, not how to hack.",
      },
      {
        name: "CRISC",
        note: "Risk-focused. Good for mid-level GRC moving toward risk management.",
      },
      {
        name: "CISM",
        note: "Management angle. Better when you lead programmes, not your first cert.",
      },
    ],
    careerProgression: [
      "GRC Analyst",
      "Senior GRC / Risk Analyst",
      "Compliance Manager",
      "Head of GRC or vCISO (with experience)",
    ],
    modules: [
      { name: "Risk Management", status: "coming-soon" },
      { name: "Policy and Standards", status: "coming-soon" },
      { name: "ISO 27001", status: "coming-soon" },
      { name: "NIST Cybersecurity Framework", status: "coming-soon" },
      { name: "Audit Preparation", status: "coming-soon" },
      { name: "Third-Party Risk", status: "coming-soon" },
      { name: "Regulatory Compliance", status: "coming-soon" },
      { name: "Business Continuity", status: "coming-soon" },
    ],
    ...GRC_ANALYST_ENRICHED,
  },
  {
    slug: "appsec-engineer",
    name: "AppSec Engineer",
    domain: "Application and Product Security",
    domainId: "application-product-security",
    level: "Mid to Senior",
    v1: true,
    cabinetPath: "appsec",
    dayToDay:
      "You work inside product teams: reviewing code, running SAST and DAST, threat modeling features, and fixing how engineers ship securely. You are in PRs and design reviews, not only at the end of a release.",
    background:
      "Software development experience is close to essential. QA or infra people can transition with strong coding practice. You need to read code in at least one mainstream language and explain fixes without lecturing.",
    typicalWeek: [
      "Monday: Secure design review for a new API feature.",
      "Tuesday: Triage Semgrep findings and pair with a team on SQL injection fix.",
      "Wednesday: Threat model update for payment flow.",
      "Thursday: Pipeline workshop: add container scan gate in CI.",
      "Friday: Office hours for developers on authentication library choices.",
    ],
    salaries: SALARY_APPSEC,
    industries: [
      "SaaS and fintech",
      "E-commerce platforms",
      "Banks with in-house development",
      "Consultancies with AppSec practices",
      "Any organisation shipping customer-facing software",
    ],
    toolsFree: [
      "Semgrep",
      "OWASP ZAP",
      "Burp Suite Community",
      "Dependency-Check",
      "Trivy",
      "Gitleaks",
    ],
    toolsEnterprise: [
      "Checkmarx / Veracode",
      "Burp Suite Professional",
      "Snyk Enterprise",
      "GitHub Advanced Security",
      "Contrast or Invicti (DAST)",
    ],
    certs: [
      {
        name: "OSWE / WEB-300",
        note: "Advanced web exploitation. Optional. Strong signal for offensive-leaning AppSec.",
      },
      {
        name: "CSSLP",
        note: "Broad secure lifecycle cert. Less hands-on than a portfolio of reviews and labs.",
      },
      {
        name: "GWAPT",
        note: "Web application pentest focus. Useful if your role includes testing as well as review.",
      },
    ],
    careerProgression: [
      "Application Security Engineer",
      "Senior AppSec Engineer",
      "Product Security Lead",
      "Head of Application Security",
    ],
    modules: [
      { name: "Static Application Security Testing", status: "coming-soon" },
      { name: "OWASP Top 10", status: "coming-soon" },
      { name: "Threat Modeling", status: "coming-soon" },
      { name: "Secure Code Review", status: "coming-soon" },
      { name: "Dynamic Application Security Testing", status: "coming-soon" },
      { name: "DevSecOps Foundations", status: "coming-soon" },
      { name: "Secure SDLC", status: "coming-soon" },
    ],
    ...APPSEC_ENGINEER_ENRICHED,
  },
  {
    slug: "api-security-engineer",
    name: "API Security Engineer",
    domain: "Application and Product Security",
    domainId: "application-product-security",
    level: "Mid",
    v1: true,
    cabinetPath: "api-security",
    dayToDay:
      "You test and design security around APIs: authentication flows, object-level access, rate limits, and business logic flaws. Most products are APIs first now, so you work with Postman collections, gateway configs, and backend teams daily.",
    background:
      "Backend or AppSec background fits best. You should understand OAuth, JWT, and REST or GraphQL patterns. Web-only testers need to learn how machines call machines, not just browsers.",
    typicalWeek: [
      "Monday: Review OpenAPI spec for a new partner integration.",
      "Tuesday: Run BOLA tests on staging with automated collection.",
      "Wednesday: JWT implementation review with platform team.",
      "Thursday: Rate limiting and abuse case workshop.",
      "Friday: Write findings report for gateway misconfiguration.",
    ],
    salaries: SALARY_API_SECURITY,
    industries: [
      "Fintech and payment platforms",
      "SaaS with public APIs",
      "Mobile-first companies (API backends)",
      "Banks and open banking programmes",
      "Marketplaces and platform businesses",
    ],
    toolsFree: [
      "Postman",
      "OWASP ZAP",
      "jwt_tool",
      "Burp Suite Community",
      "OpenAPI linters",
    ],
    toolsEnterprise: [
      "42Crunch (API spec security)",
      "Salt Security / Noname (API security platforms)",
      "Burp Suite Professional",
      "Kong or Apigee with security plugins",
    ],
    certs: [
      {
        name: "OWASP API Security learning (no single gold-standard cert)",
        note: "Build a Postman collection and written report instead. That is what hiring managers ask for.",
      },
      {
        name: "GWAPT",
        note: "Covers web and API attack surface. Relevant if you also test traditional web apps.",
      },
    ],
    careerProgression: [
      "API Security Engineer",
      "Senior API / Product Security Engineer",
      "Application Security Lead",
      "Security Architect (product focus)",
    ],
    modules: [
      { name: "API Security Testing", status: "coming-soon" },
      { name: "OWASP API Top 10", status: "coming-soon" },
      { name: "API Threat Modeling", status: "coming-soon" },
      { name: "API Authentication", status: "coming-soon" },
      { name: "OAuth Security", status: "coming-soon" },
      { name: "API Security Review", status: "coming-soon" },
    ],
    ...API_SECURITY_ENGINEER_ENRICHED,
  },
] as const;
